// https://en.wikipedia.org/wiki/List_of_cities_in_Japan
export default [
  '東京特別区部',//Special wards of Tokyo
  '横浜市',//Yokohama
  '大阪市',//Osaka
  '名古屋市',//Nagoya
  '札幌市',//Sapporo
  '福岡市',//Fukuoka
  '川崎市',//Kawasaki
  '神戸市',//Kobe
  '京都市',//Kyoto
  'さいたま市',//Saitama
  '広島市',//Hiroshima
  '仙台市',//Sendai
  '千葉市',//Chiba
  '北九州市',//Kitakyushu
  '世田谷区',//Setagaya
  '堺市',//Sakai
  '新潟市',//Niigata
  '練馬区',//Nerima
  '熊本市',//Kumamoto
  '相模原市',//Sagamihara
  '岡山市',//Okayama
  '大田区',//Ōta
  '静岡市',//Shizuoka
  '浜松市',//Hamamatsu
  '江戸川区',//Edogawa
  '足立区',//Adachi
  '鹿児島市',//Kagoshima
  '船橋市',//Funabashi
  '八王子市',//Hachiōji
  '川口市',//Kawaguchi
  '姫路市',//Himeji
  '杉並区',//Suginami
  '板橋区',//Itabashi
  '松山市',//Matsuyama
  '東大阪市',//Higashiōsaka
  '宇都宮市',//Utsunomiya
  '松戸市',//Matsudo
  '西宮市',//Nishinomiya
  '倉敷市',//Kurashiki
  '市川市',//Ichikawa
  '大分市',//Ōita
  '福山市',//Fukuyama
  '尼崎市',//Amagasaki
  '金沢市',//Kanazawa
  '長崎市',//Nagasaki
  '江東区',//Kōtō
  '葛飾区',//Katsushika
  '横須賀市',//Yokosuka
  '富山市',//Toyama
  '豊田市',//Toyota
  '高松市',//Takamatsu
  '町田市',//Machida
  '岐阜市',//Gifu
  '枚方市',//Hirakata
  '藤沢市',//Fujisawa
  '柏市',//Kashiwa
  '豊中市',//Toyonaka
  '豊橋市',//Toyohashi
  '一宮市',//Ichinomiya
  '和歌山市',//Wakayama
  '岡崎市',//Okazaki
  '宮崎市',//Miyazaki
  '奈良市',//Nara
  '長野市',//Nagano
  '吹田市',//Suita
  '高槻市',//Takatsuki
  '品川区',//Shinagawa
  '旭川市',//Asahikawa
  'いわき市',//Iwaki
  '高知市',//Kōchi
  '高崎市',//Takasaki
  '郡山市',//Kōriyama
  '所沢市',//Tokorozawa
  '川越市',//Kawagoe
  '北区',//Kita
  '秋田市',//Akita
  '大津市',//Ōtsu
  '越谷市',//Koshigaya
  '前橋市',//Maebashi
  '那覇市',//Naha
  '中野区',//Nakano
  '新宿区',//Shinjuku
  '四日市市',//Yokkaichi
  '青森市',//Aomori
  '久留米市',//Kurume
  '春日井市',//Kasugai
  '盛岡市',//Morioka
  '明石市',//Akashi
  '福島市',//Fukushima
  '津市',//Tsu
  '下関市',//Shimonoseki
  '長岡市',//Nagaoka
  '市原市',//Ichihara
  '函館市',//Hakodate
  '八尾市',//Yao
  '茨木市',//Ibaraki
  '福井市',//Fukui
  '目黒区',//Meguro
  '加古川市',//Kakogawa
  '徳島市',//Tokushima
  '水戸市',//Mito
  '平塚市',//Hiratsuka
  '豊島区',//Toshima
  '山形市',//Yamagata
  '佐世保市',//Sasebo
  '府中市',//Fuchū
  '呉市',//Kure
  '八戸市',//Hachinohe
  '佐賀市',//Saga
  '寝屋川市',//Neyagawa
  '松本市',//Matsumoto
  '草加市',//Sōka
  '墨田区',//Sumida
  '富士市',//Fuji
  '春日部市',//Kasukabe
  '茅ヶ崎市',//Chigasaki
  '厚木市',//Atsugi
  '大和市',//Yamato
  '上尾市',//Ageo
  '宝塚市',//Takarazuka
  '調布市',//Chōfu
  '太田市',//Ōta
  'つくば市',//Tsukuba
  '西東京市',//Nishitōkyō
  '沼津市',//Numazu
  '上越市',//Jōetsu
  '渋谷区',//Shibuya
  '港区',//Minato
  '熊谷市',//Kumagaya
  '伊勢崎市',//Isesaki
  '岸和田市',//Kishiwada
  '鳥取市',//Tottori
  '甲府市',//Kōfu
  '小田原市',//Odawara
  '鈴鹿市',//Suzuka
  '松江市',//Matsue
  '日立市',//Hitachi
  '文京区',//Bunkyō
  '荒川区',//Arakawa
  '伊丹市',//Itami
  '山口市',//Yamaguchi
  '宇治市',//Uji
  '東広島市',//Higashihiroshima
  '弘前市',//Hirosaki
  '小平市',//Kodaira
  '八千代市',//Yachiyo
  '釧路市',//Kushiro
  '三鷹市',//Mitaka
  '日野市',//Hino
  '和泉市',//Izumi
  '高岡市',//Takaoka
  '宇部市',//Ube
  '安城市',//Anjō
  '立川市',//Tachikawa
  '苫小牧市',//Tomakomai
  '鎌倉市',//Kamakura
  '磐田市',//Iwata
  '佐倉市',//Sakura
  '今治市',//Imabari
  '松阪市',//Matsusaka
  '都城市',//Miyakonojō
  '秦野市',//Hadano
  '台東区',//Taitō
  '帯広市',//Obihiro
  '石巻市',//Ishinomaki
  '大垣市',//Ōgaki
  '小山市',//Oyama
  '上田市',//Ueda
  '豊川市',//Toyokawa
  '習志野市',//Narashino
  '浦安市',//Urayasu
  '足利市',//Ashikaga
  '川西市',//Kawanishi
  '流山市',//Nagareyama
  '狭山市',//Sayama
  '新座市',//Niiza
  'ひたちなか市',//Hitachinaka
  '野田市',//Noda
  '周南市',//Shūnan
  '多摩市',//Tama
  '米子市',//Yonago
  '小牧市',//Komaki
  '入間市',//Iruma
  '尾道市',//Onomichi
  '岩国市',//Iwakuni
  '東村山市',//Higashimurayama
  '守口市',//Moriguchi
  '深谷市',//Fukaya
  '出雲市',//Izumo
  '各務原市',//Kakamigahara
  '刈谷市',//Kariya
  '古河市',//Koga
  '土浦市',//Tsuchiura
  '諫早市',//Isahaya
  '青梅市',//Ōme
  '桑名市',//Kuwana
  '鶴岡市',//Tsuruoka
  '武蔵野市',//Musashino
  '稲沢市',//Inazawa
  '大崎市',//Ōsaki
  '八代市',//Yatsushiro
  '伊勢市',//Ise
  '我孫子市',//Abiko
  '延岡市',//Nobeoka
  '瀬戸市',//Seto
  '飯塚市',//Iizuka
  '小樽市',//Otaru
  '門真市',//Kadoma
  '藤枝市',//Fujieda
  '会津若松市',//Aizuwakamatsu
  '唐津市',//Karatsu
  '三郷市',//Misato
  '沖縄市',//Okinawa
  '奥州市',//Ōshū
  '箕面市',//Minoh
  '霧島市',//Kirishima
  '座間市',//Zama
  '大牟田市',//Ōmuta
  '別府市',//Beppu
  '朝霞市',//Asaka
  '海老名市',//Ebina
  '大東市',//Daitō
  '松原市',//Matsubara
  '桐生市',//Kiryū
  '成田市',//Narita
  '橿原市',//Kashihara
  '北見市',//Kitami
  '木更津市',//Kisarazu
  '草津市',//Kusatsu
  '新居浜市',//Niihama
  '一関市',//Ichinoseki
  '佐野市',//Sano
  '富田林市',//Tondabayashi
  '富士宮市',//Fujinomiya
  '江別市',//Ebetsu
  '焼津市',//Yaizu
  '鴻巣市',//Kōnosu
  '国分寺市',//Kokubunji
  '掛川市',//Kakegawa
  '戸田市',//Toda
  '羽曳野市',//Habikino
  '半田市',//Handa
  '東近江市',//Higashiōmi
  '防府市',//Hōfu
  '那須塩原市',//Nasushiobara
  '東久留米市',//Higashikurume
  '生駒市',//Ikoma
  '廿日市市',//Hatsukaichi
  '小金井市',//Koganei
  '酒田市',//Sakata
  '多治見市',//Tajimi
  '河内長野市',//Kawachinagano
  'うるま市',//Uruma
  '三田市',//Sanda
  '長浜市',//Nagahama
  '西条市',//Saijō
  '三島市',//Mishima
  '昭島市',//Akishima
  '彦根市',//Hikone
  '筑西市',//Chikusei
  '白山市',//Hakusan
  '丸亀市',//Marugame
  '取手市',//Toride
  '津山市',//Tsuyama
  '小松市',//Komatsu
  '浦添市',//Urasoe
  '春日市',//Kasuga
  '飯田市',//Iida
  '東海市',//Tōkai
  '西尾市',//Nishio
  '鹿屋市',//Kanoya
  '富士見市',//Fujimi
  '中央区',//Chūō
  '鎌ヶ谷市',//Kamagaya
  '池田市',//Ikeda
  'ふじみ野市',//Fujimino
  '花巻市',//Hanamaki
  '鹿沼市',//Kanuma
  '新発田市',//Shibata
  '三原市',//Mihara
  '三条市',//Sanjō
  '横手市',//Yokote
  '伊勢原市',//Isehara
  '薩摩川内市',//Satsumasendai
  '糸島市',//Itoshima
  '佐久市',//Saku
  '江南市',//Kōnan
  '坂戸市',//Sakado
  '伊賀市',//Iga
  '泉佐野市',//Izumisano
  '可児市',//Kani
  '筑紫野市',//Chikushino
  '安曇野市',//Azumino
  '島田市',//Shimada
  '高山市',//Takayama
  '宗像市',//Munakata
  '北上市',//Kitakami
  '射水市',//Imizu
  '高砂市',//Takasago
  '千歳市',//Chitose
  '大野城市',//Ōnojō
  '甲賀市',//Kōka
  '亀岡市',//Kameoka
  '神栖市',//Kamisu
  '柏崎市',//Kashiwazaki
  '室蘭市',//Muroran
  '天草市',//Amakusa
  '茂原市',//Mobara
  '関市',//Seki
  '芦屋市',//Ashiya
  '坂井市',//Sakai
  '日光市',//Nikkō
  '米沢市',//Yonezawa
  '四国中央市',//Shikokuchūō
  '宜野湾市',//Ginowan
  '大仙市',//Daisen
  '東松山市',//Higashimatsuyama
  '舞鶴市',//Maizuru
  '貝塚市',//Kaizuka
  '大和郡山市',//Yamatokōriyama
  '大村市',//Ōmura
  '君津市',//Kimitsu
  '岩見沢市',//Iwamizawa
  '御殿場市',//Gotemba
  '豊岡市',//Toyooka
  '由利本荘市',//Yurihonjō
  '行田市',//Gyōda
  '越前市',//Echizen
  '登米市',//Tome
  'あま市',//Ama
  '宇和島市',//Uwajima
  '渋川市',//Shibukawa
  '四街道市',//Yotsukaidō
  '香取市',//Katori
  '袋井市',//Fukuroi
  '知多市',//Chita
  '摂津市',//Settsu
  '中津市',//Nakatsu
  '飯能市',//Hannō
  '三木市',//Miki
  '中津川市',//Nakatsugawa
  '大府市',//Ōbu
  '燕市',//Tsubame
  '蒲郡市',//Gamagōri
  '綾瀬市',//Ayase
  '本庄市',//Honjō
  '栃木市',//Tochigi
  '近江八幡市',//Ōmihachiman
  '東大和市',//Higashiyamato
  '名張市',//Nabari
  'たつの市',//Tatsuno
  '日進市',//Nisshin
  '福知山市',//Fukuchiyama
  '城陽市',//Jōyō
  '稲城市',//Inagi
  '笠間市',//Kasama
  '大館市',//Ōdate
  '石岡市',//Ishioka
  '田辺市',//Tanabe
  '須賀川市',//Sukagawa
  'あきる野市',//Akiruno
  '北名古屋市',//Kitanagoya
  '龍ヶ崎市',//Ryūgasaki
  '牛久市',//Ushiku
  '尾張旭市',//Owariasahi
  '長岡京市',//Nagaokakyō
  '館林市',//Tatebayashi
  '佐伯市',//Saiki
  '八潮市',//Yashio
  '和光市',//Wakō
  '大田原市',//Ōtawara
  '狛江市',//Komae
  '泉大津市',//Izumiōtsu
  '栗原市',//Kurihara
  '交野市',//Katano
  '阿南市',//Anan
  '柏原市',//Kashiwara
  '八街市',//Yachimata
  '犬山市',//Inuyama
  '桶川市',//Okegawa
  '姶良市',//Aira
  '守山市',//Moriyama
  '甲斐市',//Kai
  '八幡市',//Yawata
  '加賀市',//Kaga
  '清瀬市',//Kiyose
  '国立市',//Kunitachi
  '碧南市',//Hekinan
  '香芝市',//Kashiba
  '柳川市',//Yanagawa
  '日田市',//Hita
  '銚子市',//Chōshi
  '南アルプス市',//Minami-Alps
  '伊東市',//Itō
  '伊那市',//Ina
  '南相馬市',//Minamisōma
  '久喜市',//Kuki
  '笛吹市',//Fuefuki
  '玉名市',//Tamana
  '天理市',//Tenri
  '蕨市',//Warabi
  '鶴ヶ島市',//Tsurugashima
  '行橋市',//Yukuhashi
  '三豊市',//Mitoyo
  '旭市',//Asahi
  '北本市',//Kitamoto
  '名取市',//Natori
  '大和高田市',//Yamatotakada
  '丹波市',//Tamba
  '秩父市',//Chichibu
  '豊明市',//Toyoake
  '恵庭市',//Eniwa
  '藤岡市',//Fujioka
  '太宰府市',//Dazaifu
  '志木市',//Shiki
  '武蔵村山市',//Musashimurayama
  '知立市',//Chiryū
  '敦賀市',//Tsuruga
  '加須市',//Kazo
  '塩尻市',//Shiojiri
  '橋本市',//Hashimoto
  '伊達市',//Date
  '鯖江市',//Sabae
  '紀の川市',//Kinokawa
  '羽島市',//Hashima
  '鳥栖市',//Tosu
  '十和田市',//Towada
  '総社市',//Sōja
  '木津川市',//Kizugawa
  '真岡市',//Mooka
  '田原市',//Tahara
  '藤井寺市',//Fujiidera
  '常総市',//Jōsō
  '玉野市',//Tamano
  '白河市',//Shirakawa
  '津島市',//Tsushima
  '山陽小野田市',//San'yō-Onoda
  '愛西市',//Aisai
  '京田辺市',//Kyōtanabe
  '鹿嶋市',//Kashima
  '佐渡市',//Sado
  '泉南市',//Sennan
  '気仙沼市',//Kesennuma
  '観音寺市',//Kan'onji
  '天童市',//Tendō
  '蓮田市',//Hasuda
  '千曲市',//Chikuma
  '多賀城市',//Tagajō
  '日向市',//Hyūga
  '吉川市',//Yoshikawa
  '宇城市',//Uki
  '南魚沼市',//Minamiuonuma
  '鳴門市',//Naruto
  '栗東市',//Rittō
  '安中市',//Annaka
  'むつ市',//Mutsu
  'みよし市',//Miyoshi
  '二本松市',//Nihonmatsu
  '東金市',//Tōgane
  '土岐市',//Toki
  '浜田市',//Hamada
  '能代市',//Noshiro
  '京丹後市',//Kyōtango
  '五所川原市',//Goshogawara
  '桜井市',//Sakurai
  '石狩市',//Ishikari
  '名護市',//Nago
  '十日町市',//Tōkamachi
  '福生市',//Fussa
  '北広島市',//Kitahiroshima
  '印西市',//Inzai
  '七尾市',//Nanao
  '八女市',//Yame
  '高石市',//Takaishi
  '宇佐市',//Usa
  '下野市',//Shimotsuke
  '袖ヶ浦市',//Sodegaura
  '大阪狭山市',//Ōsakasayama
  '逗子市',//Zushi
  '常陸太田市',//Hitachiōta
  '小郡市',//Ogōri
  '宮古市',//Miyako
  '三次市',//Miyoshi
  '塩竈市',//Shiogama
  '朝倉市',//Asakura
  '山武市',//Sanmu
  '守谷市',//Moriya
  '長久手市',//Nagakute
  '伊万里市',//Imari
  '茅野市',//Chino
  '直方市',//Nōgata
  '四條畷市',//Shijōnawate
  '白井市',//Shiroi
  '坂東市',//Bandō
  '古賀市',//Koga
  '南砺市',//Nanto
  '羽村市',//Hamura
  '阪南市',//Hannan
  '出水市',//Izumi
  '羽生市',//Hanyū
  '志摩市',//Shima
  '山鹿市',//Yamaga
  '清須市',//Kiyosu
  '坂出市',//Sakaide
  '糸満市',//Itoman
  '笠岡市',//Kasaoka
  '五泉市',//Gosen
  '海南市',//Kainan
  '萩市',//Hagi
  '荒尾市',//Arao
  '日高市',//Hidaka
  '滝沢市',//Takizawa
  '湖南市',//Konan
  '向日市',//Mukō
  '福津市',//Fukutsu
  '恵那市',//Ena
  'さぬき市',//Sanuki
  '喜多方市',//Kitakata
  '那珂市',//Naka
  '豊見城市',//Tomigusuku
  '下松市',//Kudamatsu
  '美濃加茂市',//Minokamo
  '裾野市',//Susono
  '岡谷市',//Okaya
  '湯沢市',//Yuzawa
  '合志市',//Kōshi
  '幸手市',//Satte
  '富岡市',//Tomioka
  '氷見市',//Himi
  '光市',//Hikari
  '須坂市',//Suzaka
  '高島市',//Takashima
  '常滑市',//Tokoname
  '小美玉市',//Omitama
  '宮古島市',//Miyakojima
  '諏訪市',//Suwa
  '富谷市',//Tomiya
  '南島原市',//Minamishimabara
  '沼田市',//Numata
  '結城市',//Yūki
  '野々市市',//Nonoichi
  'みどり市',//Midori
  '富士吉田市',//Fujiyoshida
  '岩出市',//Iwade
  '白岡市',//Shiraoka
  '富里市',//Tomisato
  '登別市',//Noboribetsu
  '日置市',//Hioki
  '菊池市',//Kikuchi
  '倉吉市',//Kurayoshi
  '新城市',//Shinshiro
  '赤穂市',//Akō
  '瑞穂市',//Mizuho
  '大網白里市',//Oamishirasato
  '南あわじ市',//Minamiawaji
  '益田市',//Masuda
  '鉾田市',//Hokota
  '武雄市',//Takeo
  '田川市',//Tagawa
  '真庭市',//Maniwa
  '南国市',//Nankoku
  '亀山市',//Kameyama
  '那珂川市',//Nakagawa
  '館山市',//Tateyama
  '野洲市',//Yasu
  '牧之原市',//Makinohara
  '伊豆の国市',//Izunokuni
  '小野市',//Ono
  '大洲市',//Ōzu
  '砺波市',//Tonami
  '三浦市',//Miura
  '富津市',//Futtsu
  '島原市',//Shimabara
  '北斗市',//Hokuto
  '雲仙市',//Unzen
  '糸魚川市',//Itoigawa
  '洲本市',//Sumoto
  '北茨城市',//Kitaibaraki
  '加西市',//Kasai
  '筑後市',//Chikugo
  '稲敷市',//Inashiki
  '奄美市',//Amami
  '能美市',//Nomi
  '岩倉市',//Iwakura
  '淡路市',//Awaji
  '北杜市',//Hokuto
  '菊川市',//Kikugawa
  '桜川市',//Sakuragawa
  '常陸大宮市',//Hitachiōmiya
  'いなべ市',//Inabe
  '石垣市',//Ishigaki
  '郡上市',//Gujō
  '中野市',//Nakano
  '阿賀野市',//Agano
  '東根市',//Higashine
  '魚津市',//Uozu
  '下妻市',//Shimotsuma
  '中間市',//Nakama
  '小城市',//Ogi
  '指宿市',//Ibusuki
  '小諸市',//Komoro
  '吉野川市',//Yoshinogawa
  '岩沼市',//Iwanuma
  '湖西市',//Kosai
  'かすみがうら市',//Kasumigaura
  '嘉麻市',//Kama
  '井原市',//Ibara
  '丹波篠山市',//Tamba-Sasayama
  '南足柄市',//Minamiashigara
  '府中市',//Fuchū
  '千代田区',//Chiyoda
  '赤磐市',//Akaiwa
  '南房総市',//Minamibōsō
  '西予市',//Seiyo
  '高浜市',//Takahama
  '寒河江市',//Sagae
  '雲南市',//Unnan
  '日南市',//Nichinan
  '東松島市',//Higashimatsushima
  '弥富市',//Yatomi
  '西脇市',//Nishiwaki
  '安来市',//Yasugi
  '滝川市',//Takikawa
  '黒部市',//Kurobe
  '三沢市',//Misawa
  '臼杵市',//Usuki
  '五島市',//Gotō
  'さくら市',//Sakura
  '魚沼市',//Uonuma
  '宍粟市',//Shisō
  '田村市',//Tamura
  'みやま市',//Miyama
  '見附市',//Mitsuke
  '大船渡市',//Ōfunato
  'つくばみらい市',//Tsukubamirai
  '庄原市',//Shōbara
  'いすみ市',//Isumi
  '瑞浪市',//Mizunami
  '小松島市',//Komatsushima
  '匝瑳市',//Sōsa
  '釜石市',//Kamaishi
  '曽於市',//Soo
  '南九州市',//Minamikyūshū
  '米原市',//Maibara
  '熱海市',//Atami
  '小林市',//Kobayashi
  '豊後大野市',//Bungo-Ōno
  '南さつま市',//Minamisatsuma
  '阿波市',//Awa
  '八幡浜市',//Yawatahama
  '加東市',//Katō
  '長門市',//Nagato
  '新庄市',//Shinjō
  '大田市',//Ōda
  '南城市',//Nanjō
  '小千谷市',//Ojiya
  '行方市',//Namegata
  '備前市',//Bizen
  'つがる市',//Tsugaru
  '伊予市',//Iyo
  '瀬戸内市',//Setouchi
  '白石市',//Shiroishi
  '網走市',//Abashiri
  '北秋田市',//Kitaakita
  '相馬市',//Sōma
  '海津市',//Kaizu
  '大川市',//Ōkawa
  '山梨市',//Yamanashi
  '稚内市',//Wakkanai
  '宇土市',//Uto
  '久慈市',//Kuji
  '黒石市',//Kuroishi
  '高梁市',//Takahashi
  '下呂市',//Gero
  '四万十市',//Shimanto
  '浅口市',//Asakuchi
  '綾部市',//Ayabe
  '妙高市',//Myōkō
  '平戸市',//Hirado
  '大野市',//Ōno
  '人吉市',//Hitoyoshi
  '伊達市',//Date
  '対馬市',//Tsushima
  '五條市',//Gojō
  '南丹市',//Nantan
  '伊豆市',//Izu
  '境港市',//Sakaiminato
  '宇陀市',//Uda
  '鴨川市',//Kamogawa
  '鹿角市',//Kazuno
  '東温市',//Tōon
  '矢板市',//Yaita
  '潟上市',//Katagami
  '柳井市',//Yanai
  '由布市',//Yufu
  '葛城市',//Katsuragi
  '善通寺市',//Zentsūji
  '上山市',//Kaminoyama
  '甲州市',//Kōshū
  '新見市',//Niimi
  '御前崎市',//Omaezaki
  '東かがわ市',//Higashikagawa
  'かほく市',//Kahoku
  '本巣市',//Motosu
  '駒ヶ根市',//Komagane
  '平川市',//Hirakawa
  '南陽市',//Nan'yō
  '都留市',//Tsuru
  '男鹿市',//Oga
  '志布志市',//Shibushi
  '朝来市',//Asago
  '香南市',//Kōnan
  '滑川市',//Namerikawa
  '韮崎市',//Nirasaki
  '美馬市',//Mima
  '国東市',//Kunisaki
  '杵築市',//Kitsuki
  '神埼市',//Kanzaki
  '西都市',//Saito
  '西海市',//Saikai
  '小矢部市',//Oyabe
  '新宮市',//Shingū
  '角田市',//Kakuda
  '安芸高田市',//Akitakata
  'うきは市',//Ukiha
  '胎内市',//Tainai
  'いちき串木野市',//Ichikikushikino
  '高萩市',//Takahagi
  '相生市',//Aioi
  '中央市',//Chūō
  '本宮市',//Motomiya
  '美作市',//Mimasaka
  '輪島市',//Wajima
  '小浜市',//Obama
  '鹿島市',//Kashima
  '大町市',//Ōmachi
  '東御市',//Tōmi
  '有田市',//Arida
  '御所市',//Gose
  '潮来市',//Itako
  '上天草市',//Kami-Amakusa
  '三好市',//Miyoshi
  '仙北市',//Semboku
  '加茂市',//Kamo
  '宮若市',//Miyawaka
  'あわら市',//Awara
  '二戸市',//Ninohe
  '遠野市',//Tōno
  '那須烏山市',//Nasukarasuyama
  '壱岐市',//Iki
  '長井市',//Nagai
  '村上市',//Murakami
  '伊佐市',//Isa
  '八幡平市',//Hachimantai
  '名寄市',//Nayoro
  '大月市',//Ōtsuki
  '山県市',//Yamagata
  '竹原市',//Takehara
  '土佐市',//Tosa
  '大竹市',//Ōtake
  '嬉野市',//Ureshino
  '阿蘇市',//Aso
  '香美市',//Kami
  '根室市',//Nemuro
  '江田島市',//Etajima
  'にかほ市',//Nikaho
  '上野原市',//Uenohara
  '水俣市',//Minamata
  '飛騨市',//Hida
  '村山市',//Murayama
  '豊前市',//Buzen
  '養父市',//Yabu
  '江津市',//Gōtsu
  '御坊市',//Gobō
  '勝山市',//Katsuyama
  '松浦市',//Matsuura
  '下田市',//Shimoda
  '須崎市',//Susaki
  '竹田市',//Taketa
  '美唄市',//Bibai
  '豊後高田市',//Bungotakada
  '枕崎市',//Makurazaki
  '紋別市',//Monbetsu
  '阿久根市',//Akune
  '飯山市',//Iiyama
  '留萌市',//Rumoi
  '羽咋市',//Hakui
  '陸前高田市',//Rikuzentakata
  '富良野市',//Furano
  '宿毛市',//Sukumo
  '深川市',//Fukagawa
  '美祢市',//Mine
  '美濃市',//Mino
  'えびの市',//Ebino
  '鳥羽市',//Toba
  '多久市',//Taku
  '士別市',//Shibetsu
  '勝浦市',//Katsuura
  '串間市',//Kushima
  '尾鷲市',//Owase
  '宮津市',//Miyazu
  '津久見市',//Tsukumi
  '安芸市',//Aki
  '熊野市',//Kumano
  '尾花沢市',//Obanazawa
  '垂水市',//Tarumizu
  '砂川市',//Sunagawa
  '西之表市',//Nishinoomote
  '珠洲市',//Suzu
  '土佐清水市',//Tosashimizu
  '芦別市',//Ashibetsu
  '室戸市',//Muroto
  '赤平市',//Akabira
  '三笠市',//Mikasa
  '夕張市',//Yūbari
  '歌志内市',//Utashinai
]