// hand-segmented sentences, with the head-tag we expect for each token.
// '|' separates tokens, and 'word/Tag' pins a tag onto that token.
export default [
  '私/Pronoun|は/Particle|学生/Noun|です/Copula',
  'これ/Pronoun|は/Particle|ペン/Noun|です/Copula',
  '彼/Pronoun|は/Particle|毎日/Noun|学校/Noun|に/Particle|行きます/Verb',
  '昨日/Noun|映画/Noun|を/Particle|見ました/Verb',
  '本/Noun|を/Particle|読んでいる/Verb|人/Noun',
  '東京/Noun|へ/Particle|行った/Verb|こと/Noun|が/Particle|あります/Verb',
  '子供/Noun|に/Particle|野菜/Noun|を/Particle|食べさせる/Verb',
  '雨/Noun|が/Particle|降ったら/Verb|行きません/Verb',
  '大きい/Adjective|犬/Noun|と/Particle|小さな/Adjective|猫/Noun',
  'ご飯/Noun|を/Particle|食べたくない/Verb',
  '今日/Noun|は/Particle|天気/Noun|が/Particle|いい/Adjective|です/Copula|ね/Particle',
  '先生/Noun|に/Particle|褒められました/Verb',
  '日本語/Noun|を/Particle|勉強しています/Verb',
  '彼女/Pronoun|に/Particle|花/Noun|を/Particle|あげた/Verb',
  '早く/Adverb|走れ/Verb',
  'この/Determiner|本/Noun|は/Particle|高かった/Adjective',
  '静か/Adjective|な/Particle|人/Noun',
  '彼/Pronoun|が/Particle|来る/Verb|か/Particle|どう/Adverb|か/Particle|分からない/Verb',
  '駅/Noun|は/Particle|どこ/Pronoun|です/Copula|か/Particle',
  '水/Noun|を/Particle|飲みたい/Verb',
  '手紙/Noun|を/Particle|書いて/Verb|ください/Verb',
  '毎朝/Noun|コーヒー/Noun|を/Particle|飲みます/Verb',
  '彼/Pronoun|は/Particle|日本/Noun|に/Particle|住んでいます/Verb',
  '難しい/Adjective|問題/Noun|です/Copula',
  '一緒/Noun|に/Particle|行こう/Verb',
]
